"""init

Revision ID: 045c41f06b8d
Revises:
Create Date: 2026-04-10 12:32:41.082547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector

# revision identifiers, used by Alembic.
revision: str = '045c41f06b8d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_points',
    sa.Column('id', sa.UUID(), nullable=False, comment='知识点唯一标识 UUID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='文档标题（通常取自文件名或用户输入）'),
    sa.Column('file_type', sa.String(length=20), nullable=False, comment='文件类型：pdf, md, docx, txt 等'),
    sa.Column('object_path', sa.String(length=500), nullable=False, comment='文件在 MinIO 中的存储路径（如 documents/uuid_filename.pdf）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='标记当前知识点分块向量是否激活'),
    sa.Column('retrieval_count', sa.Integer(), nullable=False, comment='知识点被检索次数（所有chunk检索次数之和）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_points_retrieval_count_desc', 'knowledge_points', ['retrieval_count'], unique=False)
    op.create_table('question_banks',
    sa.Column('id', sa.UUID(), nullable=False, comment='题库唯一标识 UUID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='题库名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='题库描述'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retrieval_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='日志唯一标识 UUID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='发起检索的用户 ID'),
    sa.Column('conversation_id', sa.UUID(), nullable=True, comment='所属会话 ID，若检索发生在对话中则记录，独立检索可为空'),
    sa.Column('original_query', sa.Text(), nullable=False, comment='用户输入的原始查询语句'),
    sa.Column('rewritten_statement', sa.Text(), nullable=True, comment='查询改写后的语句（如 HyDE、多查询融合等），未改写则为空'),
    sa.Column('rewritten_question', sa.Text(), nullable=True, comment='查询改写后的问题形式（与 statement 可能不同），未改写则为空'),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='检索配置快照，如 top_k、相似度阈值、使用的模型、混合检索权重等'),
    sa.Column('direct_hit_kp_ids', postgresql.ARRAY(sa.UUID()), nullable=False, comment='直接命中（如关键词精确匹配）的知识点 ID 列表'),
    sa.Column('mapped_kp_ids', postgresql.ARRAY(sa.UUID()), nullable=False, comment='经过映射（如实体链接、同义词扩展）后命中的知识点 ID 列表'),
    sa.Column('final_kp_ids', postgresql.ARRAY(sa.UUID()), nullable=False, comment='最终返回给用户的知识点 ID 列表（去重排序后）'),
    sa.Column('scores_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='每个最终知识点的详细评分，如 BM25 分数、向量相似度、融合分数等'),
    sa.Column('cache_hit', sa.Boolean(), nullable=False, comment='是否命中缓存（完全相同的查询直接返回缓存结果）'),
    sa.Column('duration_ms', sa.BigInteger(), nullable=False, comment='检索耗时（毫秒），包括向量搜索、重排序、融合等全流程时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='日志记录创建时间（UTC）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_retrieval_logs_cache_hit', 'retrieval_logs', ['cache_hit'], unique=False)
    op.create_index('ix_retrieval_logs_created_at', 'retrieval_logs', ['created_at'], unique=False)
    op.create_index('ix_retrieval_logs_user_id', 'retrieval_logs', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='用户唯一标识 UUID'),
    sa.Column('phone', sa.String(length=11), nullable=False, comment='用户手机号码（中国大陆 11 位）'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希值（bcrypt / argon2）'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='用户角色：user（普通用户） / admin（管理员）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='账户状态：active（正常） / disabled（禁用）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('vectorization_jobs',
    sa.Column('id', sa.UUID(), nullable=False, comment='任务唯一标识 UUID'),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='job_status', create_constraint=True), nullable=False, comment='任务状态：pending（等待中）、running（执行中）、success（成功）、failed（失败）'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='任务进度百分比，取值范围 0-100'),
    sa.Column('total_questions', sa.Integer(), nullable=False, comment='本次任务需要处理的题目总数'),
    sa.Column('processed_questions', sa.Integer(), nullable=False, comment='已成功处理的题目数量'),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True, comment='关联的 Celery 任务 ID，用于异步任务追踪与管理'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='任务失败时的错误详细信息'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='任务实际开始执行的时间（UTC）'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='任务完成（成功或失败）的时间（UTC）'),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='额外元数据，如触发参数、重试信息等'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False, comment='会话唯一标识 UUID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='拥有该会话的用户 ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment="会话标题，默认值为 'New Conversation'"),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记：True 表示已删除，查询时应过滤'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_is_deleted', 'conversations', ['is_deleted'], unique=False)
    op.create_index('ix_conversations_user_id', 'conversations', ['user_id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.UUID(), nullable=False, comment='任务唯一标识 UUID'),
    sa.Column('knowledge_point_id', sa.UUID(), nullable=True, comment='入库成功后创建的知识点 ID，失败时为 NULL'),
    sa.Column('object_path', sa.String(length=500), nullable=False, comment='文件在 MinIO 中的完整路径（如 documents/uuid_filename.pdf）'),
    sa.Column('file_type', sa.String(length=20), nullable=False, comment='文件类型：pdf、md、docx、txt 等'),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='job_status', create_constraint=True), nullable=False, comment='任务状态：pending（等待） / running（执行中） / success（成功） / failed（失败）'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='任务进度百分比，取值范围 0-100'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='任务失败时的详细错误信息'),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True, comment='关联的 Celery 任务 ID，用于异步任务追踪与管理'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_jobs_created_at', 'ingestion_jobs', ['created_at'], unique=False)
    op.create_index('ix_ingestion_jobs_kp_id', 'ingestion_jobs', ['knowledge_point_id'], unique=False)
    op.create_index('ix_ingestion_jobs_status', 'ingestion_jobs', ['status'], unique=False)
    op.create_table('knowledge_point_chunks',
    sa.Column('id', sa.UUID(), nullable=False, comment='分块唯一标识 UUID'),
    sa.Column('knowledge_point_id', sa.UUID(), nullable=False, comment='所属知识点 ID'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='分块在文档中的序号（从 0 开始）'),
    sa.Column('content', sa.Text(), nullable=False, comment='分块包含的文本内容'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True, comment='文本向量表示（1024 维），用于相似度检索。可能为空表示等待异步生成'),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='分块元数据，如页码、标题层级、语言等'),
    sa.Column('retrieval_count', sa.Integer(), nullable=False, comment='该分块被检索命中的次数'),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_point_chunks_chunk_index', 'knowledge_point_chunks', ['chunk_index'], unique=False)
    op.create_index('ix_knowledge_point_chunks_kp_id', 'knowledge_point_chunks', ['knowledge_point_id'], unique=False)
    op.create_index('ix_knowledge_point_chunks_kp_id_order', 'knowledge_point_chunks', ['knowledge_point_id', 'chunk_index'], unique=False)
    op.create_index('ix_knowledge_point_chunks_retrieval_count', 'knowledge_point_chunks', ['retrieval_count'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False, comment='题目唯一标识 UUID'),
    sa.Column('bank_id', sa.UUID(), nullable=False, comment='所属题库 ID'),
    sa.Column('external_id', sa.String(length=255), nullable=True, comment='外部标识，用于幂等导入'),
    sa.Column('content_hash', sa.String(length=64), nullable=False, comment='题目关键字段（题干+选项+答案）的 SHA256 哈希值'),
    sa.Column('question_text', sa.Text(), nullable=False, comment='题干文本'),
    sa.Column('question_type', sa.Enum('SINGLE', 'MULTIPLE', 'TRUE_FALSE', 'SHORT_ANSWER', name='questiontype'), nullable=False, comment='题型'),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='选项列表，每个选项包含 label 和 text'),
    sa.Column('answer', sa.Text(), nullable=True, comment='标准答案'),
    sa.Column('explanation', sa.Text(), nullable=True, comment='答案解析'),
    sa.Column('is_dirty', sa.Boolean(), nullable=False, comment='脏标记,为 True 时表示需要重新生成向量'),
    sa.Column('question_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True, comment='题干文本的向量嵌入(1024维)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['question_banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_content_hash'), 'questions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_questions_external_id'), 'questions', ['external_id'], unique=False)
    op.create_table('chat_runs',
    sa.Column('id', sa.UUID(), nullable=False, comment='本次运行的唯一标识 UUID'),
    sa.Column('conversation_id', sa.UUID(), nullable=False, comment='所属会话 ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='发起本次运行的用户 ID'),
    sa.Column('query', sa.Text(), nullable=False, comment='用户输入的原始查询文本'),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'INTERRUPTED', name='run_status', create_constraint=True), nullable=False, comment='运行状态：pending（等待）、running（执行中）、success（成功）、failed（失败）、interrupted（中断）'),
    sa.Column('agent_state_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Agent 内部状态的 JSON 序列化快照，用于中断后恢复执行'),
    sa.Column('last_event_id', sa.String(length=36), nullable=True, comment='最后已成功发送给客户端的事件 ID，用于 SSE 重连时指定 Last-Event-ID 头部'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='运行失败时的详细错误信息'),
    sa.Column('total_steps', sa.Integer(), nullable=False, comment='本次运行已执行的 Agent 步骤总数'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='本次运行的总耗时（毫秒），成功或失败时填充'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_runs_conversation_id', 'chat_runs', ['conversation_id'], unique=False)
    op.create_index('ix_chat_runs_status', 'chat_runs', ['status'], unique=False)
    op.create_index('ix_chat_runs_user_id', 'chat_runs', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False, comment='消息唯一标识 UUID'),
    sa.Column('conversation_id', sa.UUID(), nullable=False, comment='所属会话 ID，关联 conversations 表'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='消息发送者角色：user（用户）、assistant（助手）、system（系统）'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息正文内容，支持长文本'),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='扩展元数据，如引用来源、模型参数、token 消耗等'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='NOW()', nullable=False, comment='消息创建时间（UTC）'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.create_table('question_knowledge_points',
    sa.Column('question_id', sa.UUID(), nullable=False, comment='题目 ID（外键，删除题目时自动删除关联）'),
    sa.Column('knowledge_point_id', sa.UUID(), nullable=False, comment='知识点 ID（外键，删除知识点时自动删除关联）'),
    sa.Column('relevance_weight', sa.Float(), nullable=False, comment='关联权重，值越大表示该知识点与题目越相关，可用于排序和加权检索'),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'knowledge_point_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: spatial_ref_sys and _typmod_cache are PostgreSQL/PostGIS system tables
    # and should not be modified as part of application migrations
    op.drop_table('question_knowledge_points')
    op.drop_index('ix_messages_conversation_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_chat_runs_user_id', table_name='chat_runs')
    op.drop_index('ix_chat_runs_status', table_name='chat_runs')
    op.drop_index('ix_chat_runs_conversation_id', table_name='chat_runs')
    op.drop_table('chat_runs')
    op.drop_index(op.f('ix_questions_external_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_content_hash'), table_name='questions')
    op.drop_table('questions')
    op.drop_index('ix_knowledge_point_chunks_retrieval_count', table_name='knowledge_point_chunks')
    op.drop_index('ix_knowledge_point_chunks_kp_id_order', table_name='knowledge_point_chunks')
    op.drop_index('ix_knowledge_point_chunks_kp_id', table_name='knowledge_point_chunks')
    op.drop_index('ix_knowledge_point_chunks_chunk_index', table_name='knowledge_point_chunks')
    op.drop_table('knowledge_point_chunks')
    op.drop_index('ix_ingestion_jobs_status', table_name='ingestion_jobs')
    op.drop_index('ix_ingestion_jobs_kp_id', table_name='ingestion_jobs')
    op.drop_index('ix_ingestion_jobs_created_at', table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index('ix_conversations_user_id', table_name='conversations')
    op.drop_index('ix_conversations_is_deleted', table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('vectorization_jobs')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_retrieval_logs_user_id', table_name='retrieval_logs')
    op.drop_index('ix_retrieval_logs_created_at', table_name='retrieval_logs')
    op.drop_index('ix_retrieval_logs_cache_hit', table_name='retrieval_logs')
    op.drop_table('retrieval_logs')
    op.drop_table('question_banks')
    op.drop_index('ix_knowledge_points_retrieval_count_desc', table_name='knowledge_points')
    op.drop_table('knowledge_points')
    # ### end Alembic commands ###
